version: '3.3'

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "make start"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
  web:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    volumes:
      - "./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - app
