version: '3.3'

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "make start"
    ports:
      - 3000:3000
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
  web:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
     - "8080:80"
    depends_on:
      - app
