FROM node:11.5

ENV PROJECT_ROOT /usr/src/app
WORKDIR $PROJECT_ROOT
COPY package*.json ./
RUN npm install
RUN npm install gulp
RUN npm install @babel/core @babel/cli @babel/register @babel/node
RUN npm audit fix
COPY . .

EXPOSE 3000

